name: Update Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 2 * *' # Second day of the month at 06:00 UTC

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requests
        run: pip install requests
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python update_contributions.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Latest Contributions section [bot]" || echo "No changes to commit"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update Latest Contributions section [bot]"
          title: "Update Latest Contributions section"
          body: "Automated update of the Latest Contributions section."
          branch: automate-contributions/update-readme
          delete-branch: true
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}



